### PR TITLE
Fix Fixnum warning

### PR DESCRIPTION
**Pull request by randaalex**
Here is the details referring to deprecating Fixnum
https://bugs.ruby-lang.org/issues/12005

### CODE REVIEW

**Comment by rastating** [comment]
+1 for merging this :+1:

**Comment by m45t3r** [comment]
@openhood Would be great to have a release with @randaalex fixes included.

For now, we switched to @randaalex fork for our internal projects.

**Comment by JonathanTron** [comment]
@randaalex Thanks for the fix and PR

@rastating and @m45t3r thanks for the push to release :)

**Comment by rastating** [comment]
Thanks @JonathanTron - feel free to ping me if you want someone to give it a test once it updates on rubygems :smile:

**Comment by JonathanTron** [comment]
Version 0.5.0 released on Rubygems.

/cc @rastating

**Comment by rastating** [comment]
@JonathanTron just tested - no warnings, all tests passed :smile:

**Comment by JonathanTron** [comment]
@rastating thanks for checking

**Comment by thiagokokada** [comment]
Also can confirm this fixed the warnings. Thanks @JonathanTron.

**Pull request merged**
